name: Build and deploy
on: [push]

jobs:
  compile:
      name: Compile Java Code
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Compile code
          run: mvn compile
  deploy:
      name: Build and deploy package
      needs: compile
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} # location for the settings.xml file

        - name: Build with Maven
          run: mvn -B package --file pom.xml

        - name: Publish to Gitlab package registry
          run: mvn deploy -s $GITHUB_WORKSPACE/.github/workflows/settings.xml
          env:
            DEPLOY_TOKEN: ${{ secrets.GITLAB_TOKEN }}